export interface Language {
  code: string;
  name: string;
  countryCode: string | null; // Use 2-letter country code for flag, null if no clear mapping
}

export const supportedLanguages: Language[] = [
  { code: 'en', name: '英文 (English)', countryCode: 'us' },
  { code: 'zh-TW', name: '繁體中文 (Traditional Chinese)', countryCode: 'tw' },
  { code: 'zh-CN', name: '簡體中文 (Simplified Chinese)', countryCode: 'cn' },
  { code: 'ja', name: '日文 (Japanese)', countryCode: 'jp' },
  { code: 'ko', name: '韓文 (Korean)', countryCode: 'kr' },
  { code: 'es', name: '西班牙語 (Spanish)', countryCode: 'es' },
  { code: 'fr', name: '法文 (French)', countryCode: 'fr' },
  { code: 'de', name: '德文 (German)', countryCode: 'de' },
  { code: 'ru', name: '俄語 (Russian)', countryCode: 'ru' },
  { code: 'pt', name: '葡萄牙語 (Portuguese)', countryCode: 'pt' },
  { code: 'it', name: '義大利語 (Italian)', countryCode: 'it' },
  { code: 'ar', name: '阿拉伯語 (Arabic)', countryCode: 'sa' },
  { code: 'hi', name: '印地語 (Hindi)', countryCode: 'in' },
  { code: 'af', name: '南非語 (Afrikaans)', countryCode: 'za' },
  { code: 'sq', name: '阿爾巴尼亞語 (Albanian)', countryCode: 'al' },
  { code: 'am', name: '阿姆哈拉語 (Amharic)', countryCode: 'et' },
  { code: 'hy', name: '亞美尼亞語 (Armenian)', countryCode: 'am' },
  { code: 'az', name: '亞塞拜然語 (Azerbaijani)', countryCode: 'az' },
  { code: 'eu', name: '巴斯克語 (Basque)', countryCode: 'es' }, // Basque country flag is complex
  { code: 'be', name: '白俄羅斯語 (Belarusian)', countryCode: 'by' },
  { code: 'bn', name: '孟加拉語 (Bengali)', countryCode: 'bd' },
  { code: 'bs', name: '波士尼亞語 (Bosnian)', countryCode: 'ba' },
  { code: 'bg', name: '保加利亞語 (Bulgarian)', countryCode: 'bg' },
  { code: 'ca', name: '加泰隆尼亞語 (Catalan)', countryCode: 'es' }, // Catalonia flag is complex
  { code: 'ceb', name: '宿霧語 (Cebuano)', countryCode: 'ph' },
  { code: 'ny', name: '奇切瓦語 (Chichewa)', countryCode: 'mw' },
  { code: 'co', name: '科西嘉語 (Corsican)', countryCode: 'fr' },
  { code: 'hr', name: '克羅埃西亞語 (Croatian)', countryCode: 'hr' },
  { code: 'cs', name: '捷克語 (Czech)', countryCode: 'cz' },
  { code: 'da', name: '丹麥語 (Danish)', countryCode: 'dk' },
  { code: 'nl', name: '荷蘭語 (Dutch)', countryCode: 'nl' },
  { code: 'eo', name: '世界語 (Esperanto)', countryCode: null }, // No official country
  { code: 'et', name: '愛沙尼亞語 (Estonian)', countryCode: 'ee' },
  { code: 'tl', name: '菲律賓語 (Filipino)', countryCode: 'ph' },
  { code: 'fi', name: '芬蘭語 (Finnish)', countryCode: 'fi' },
  { code: 'fy', name: '弗里西亞語 (Frisian)', countryCode: 'nl' },
  { code: 'gl', name: '加利西亞語 (Galician)', countryCode: 'es' },
  { code: 'ka', name: '喬治亞語 (Georgian)', countryCode: 'ge' },
  { code: 'el', name: '希臘語 (Greek)', countryCode: 'gr' },
  { code: 'gu', name: '古吉拉特語 (Gujarati)', countryCode: 'in' },
  { code: 'ht', name: '海地克里奧爾語 (Haitian Creole)', countryCode: 'ht' },
  { code: 'ha', name: '豪薩語 (Hausa)', countryCode: 'ng' },
  { code: 'haw', name: '夏威夷語 (Hawaiian)', countryCode: 'us' },
  { code: 'iw', name: '希伯來語 (Hebrew)', countryCode: 'il' },
  { code: 'hmn', name: '苗語 (Hmong)', countryCode: null },
  { code: 'hu', name: '匈牙利語 (Hungarian)', countryCode: 'hu' },
  { code: 'is', name: '冰島語 (Icelandic)', countryCode: 'is' },
  { code: 'ig', name: '伊博語 (Igbo)', countryCode: 'ng' },
  { code: 'id', name: '印尼語 (Indonesian)', countryCode: 'id' },
  { code: 'ga', name: '愛爾蘭語 (Irish)', countryCode: 'ie' },
  { code: 'jw', name: '爪哇語 (Javanese)', countryCode: 'id' },
  { code: 'kn', name: '卡納達語 (Kannada)', countryCode: 'in' },
  { code: 'kk', name: '哈薩克語 (Kazakh)', countryCode: 'kz' },
  { code: 'km', name: '高棉語 (Khmer)', countryCode: 'kh' },
  { code: 'ku', name: '庫德語 (Kurdish)', countryCode: 'iq' },
  { code: 'ky', name: '吉爾吉斯語 (Kyrgyz)', countryCode: 'kg' },
  { code: 'lo', name: '寮國語 (Lao)', countryCode: 'la' },
  { code: 'la', name: '拉丁語 (Latin)', countryCode: 'va' },
  { code: 'lv', name: '拉脫維亞語 (Latvian)', countryCode: 'lv' },
  { code: 'lt', name: '立陶宛語 (Lithuanian)', countryCode: 'lt' },
  { code: 'lb', name: '盧森堡語 (Luxembourgish)', countryCode: 'lu' },
  { code: 'mk', name: '馬其頓語 (Macedonian)', countryCode: 'mk' },
  { code: 'mg', name: '馬達加斯加語 (Malagasy)', countryCode: 'mg' },
  { code: 'ms', name: '馬來語 (Malay)', countryCode: 'my' },
  { code: 'ml', name: '馬拉雅拉姆語 (Malayalam)', countryCode: 'in' },
  { code: 'mt', name: '馬爾他語 (Maltese)', countryCode: 'mt' },
  { code: 'mi', name: '毛利語 (Maori)', countryCode: 'nz' },
  { code: 'mr', name: '馬拉地語 (Marathi)', countryCode: 'in' },
  { code: 'mn', name: '蒙古語 (Mongolian)', countryCode: 'mn' },
  { code: 'my', name: '緬甸語 (Burmese)', countryCode: 'mm' },
  { code: 'ne', name: '尼泊爾語 (Nepali)', countryCode: 'np' },
  { code: 'no', name: '挪威語 (Norwegian)', countryCode: 'no' },
  { code: 'ps', name: '普什圖語 (Pashto)', countryCode: 'af' },
  { code: 'fa', name: '波斯語 (Persian)', countryCode: 'ir' },
  { code: 'pl', name: '波蘭語 (Polish)', countryCode: 'pl' },
  { code: 'pa', name: '旁遮普語 (Punjabi)', countryCode: 'in' },
  { code: 'ro', name: '羅馬尼亞語 (Romanian)', countryCode: 'ro' },
  { code: 'sm', name: '薩摩亞語 (Samoan)', countryCode: 'ws' },
  { code: 'gd', name: '蘇格蘭蓋爾語 (Scots Gaelic)', countryCode: 'gb-sct' },
  { code: 'sr', name: '塞爾維亞語 (Serbian)', countryCode: 'rs' },
  { code: 'st', name: '塞索托語 (Sesotho)', countryCode: 'ls' },
  { code: 'sn', name: '紹納語 (Shona)', countryCode: 'zw' },
  { code: 'sd', name: '信德語 (Sindhi)', countryCode: 'pk' },
  { code: 'si', name: '僧伽羅語 (Sinhala)', countryCode: 'lk' },
  { code: 'sk', name: '斯洛伐克語 (Slovak)', countryCode: 'sk' },
  { code: 'sl', name: '斯洛維尼亞語 (Slovenian)', countryCode: 'si' },
  { code: 'so', name: '索馬利語 (Somali)', countryCode: 'so' },
  { code: 'su', name: '巽他語 (Sundanese)', countryCode: 'id' },
  { code: 'sw', name: '史瓦希里語 (Swahili)', countryCode: 'tz' },
  { code: 'sv', name: '瑞典語 (Swedish)', countryCode: 'se' },
  { code: 'tg', name: '塔吉克語 (Tajik)', countryCode: 'tj' },
  { code: 'ta', name: '坦米爾語 (Tamil)', countryCode: 'in' },
  { code: 'te', name: '泰盧固語 (Telugu)', countryCode: 'in' },
  { code: 'th', name: '泰語 (Thai)', countryCode: 'th' },
  { code: 'tr', name: '土耳其語 (Turkish)', countryCode: 'tr' },
  { code: 'uk', name: '烏克蘭語 (Ukrainian)', countryCode: 'ua' },
  { code: 'ur', name: '烏爾都語 (Urdu)', countryCode: 'pk' },
  { code: 'uz', name: '烏茲別克語 (Uzbek)', countryCode: 'uz' },
  { code: 'vi', name: '越南語 (Vietnamese)', countryCode: 'vn' },
  { code: 'cy', name: '威爾斯語 (Welsh)', countryCode: 'gb-wls' },
  { code: 'xh', name: '科薩語 (Xhosa)', countryCode: 'za' },
  { code: 'yi', name: '意第緒語 (Yiddish)', countryCode: null },
  { code: 'yo', name: '約魯巴語 (Yoruba)', countryCode: 'ng' },
  { code: 'zu', name: '祖魯語 (Zulu)', countryCode: 'za' },
];