export interface Language {
  code: string;
  name: string;
  countryCode: string | null; // 用於顯示旗幟的兩字母國家代碼，若無明確對應則為 null
}

export const supportedLanguages: Language[] = [
  { code: 'en', name: 'English', countryCode: 'us' },
  { code: 'zh-TW', name: 'Traditional Chinese', countryCode: 'tw' },
  { code: 'zh-CN', name: 'Simplified Chinese', countryCode: 'cn' },
  { code: 'ja', name: 'Japanese', countryCode: 'jp' },
  { code: 'ko', name: 'Korean', countryCode: 'kr' },
  { code: 'es', name: 'Spanish', countryCode: 'es' },
  { code: 'fr', name: 'French', countryCode: 'fr' },
  { code: 'de', name: 'German', countryCode: 'de' },
  { code: 'ru', name: 'Russian', countryCode: 'ru' },
  { code: 'pt', name: 'Portuguese', countryCode: 'pt' },
  { code: 'it', name: 'Italian', countryCode: 'it' },
  { code: 'ar', name: 'Arabic', countryCode: 'sa' },
  { code: 'hi', name: 'Hindi', countryCode: 'in' },
  { code: 'af', name: 'Afrikaans', countryCode: 'za' },
  { code: 'sq', name: 'Albanian', countryCode: 'al' },
  { code: 'am', name: 'Amharic', countryCode: 'et' },
  { code: 'hy', name: 'Armenian', countryCode: 'am' },
  { code: 'az', name: 'Azerbaijani', countryCode: 'az' },
  { code: 'eu', name: 'Basque', countryCode: 'es' }, // 巴斯克地區旗幟較複雜，暫用西班牙國旗
  { code: 'be', name: 'Belarusian', countryCode: 'by' },
  { code: 'bn', name: 'Bengali', countryCode: 'bd' },
  { code: 'bs', name: 'Bosnian', countryCode: 'ba' },
  { code: 'bg', name: 'Bulgarian', countryCode: 'bg' },
  { code: 'ca', name: 'Catalan', countryCode: 'es' }, // 加泰隆尼亞旗幟較複雜，暫用西班牙國旗
  { code: 'ceb', name: 'Cebuano', countryCode: 'ph' },
  { code: 'ny', name: 'Chichewa', countryCode: 'mw' },
  { code: 'co', name: 'Corsican', countryCode: 'fr' },
  { code: 'hr', name: 'Croatian', countryCode: 'hr' },
  { code: 'cs', name: 'Czech', countryCode: 'cz' },
  { code: 'da', name: 'Danish', countryCode: 'dk' },
  { code: 'nl', name: 'Dutch', countryCode: 'nl' },
  { code: 'eo', name: 'Esperanto', countryCode: null }, // 世界語沒有官方國旗
  { code: 'et', name: 'Estonian', countryCode: 'ee' },
  { code: 'tl', name: 'Filipino', countryCode: 'ph' },
  { code: 'fi', name: 'Finnish', countryCode: 'fi' },
  { code: 'fy', name: 'Frisian', countryCode: 'nl' },
  { code: 'gl', name: 'Galician', countryCode: 'es' },
  { code: 'ka', name: 'Georgian', countryCode: 'ge' },
  { code: 'el', name: 'Greek', countryCode: 'gr' },
  { code: 'gu', name: 'Gujarati', countryCode: 'in' },
  { code: 'ht', name: 'Haitian Creole', countryCode: 'ht' },
  { code: 'ha', name: 'Hausa', countryCode: 'ng' },
  { code: 'haw', name: 'Hawaiian', countryCode: 'us' },
  { code: 'iw', name: 'Hebrew', countryCode: 'il' },
  { code: 'hmn', name: 'Hmong', countryCode: null },
  { code: 'hu', name: 'Hungarian', countryCode: 'hu' },
  { code: 'is', name: 'Icelandic', countryCode: 'is' },
  { code: 'ig', name: 'Igbo', countryCode: 'ng' },
  { code: 'id', name: 'Indonesian', countryCode: 'id' },
  { code: 'ga', name: 'Irish', countryCode: 'ie' },
  { code: 'jw', name: 'Javanese', countryCode: 'id' },
  { code: 'kn', name: 'Kannada', countryCode: 'in' },
  { code: 'kk', name: 'Kazakh', countryCode: 'kz' },
  { code: 'km', name: 'Khmer', countryCode: 'kh' },
  { code: 'ku', name: 'Kurdish', countryCode: 'iq' },
  { code: 'ky', name: 'Kyrgyz', countryCode: 'kg' },
  { code: 'lo', name: 'Lao', countryCode: 'la' },
  { code: 'la', name: 'Latin', countryCode: 'va' },
  { code: 'lv', name: 'Latvian', countryCode: 'lv' },
  { code: 'lt', name: 'Lithuanian', countryCode: 'lt' },
  { code: 'lb', name: 'Luxembourgish', countryCode: 'lu' },
  { code: 'mk', name: 'Macedonian', countryCode: 'mk' },
  { code: 'mg', name: 'Malagasy', countryCode: 'mg' },
  { code: 'ms', name: 'Malay', countryCode: 'my' },
  { code: 'ml', name: 'Malayalam', countryCode: 'in' },
  { code: 'mt', name: 'Maltese', countryCode: 'mt' },
  { code: 'mi', name: 'Maori', countryCode: 'nz' },
  { code: 'mr', name: 'Marathi', countryCode: 'in' },
  { code: 'mn', name: 'Mongolian', countryCode: 'mn' },
  { code: 'my', name: 'Burmese', countryCode: 'mm' },
  { code: 'ne', name: 'Nepali', countryCode: 'np' },
  { code: 'no', name: 'Norwegian', countryCode: 'no' },
  { code: 'ps', name: 'Pashto', countryCode: 'af' },
  { code: 'fa', name: 'Persian', countryCode: 'ir' },
  { code: 'pl', name: 'Polish', countryCode: 'pl' },
  { code: 'pa', name: 'Punjabi', countryCode: 'in' },
  { code: 'ro', name: 'Romanian', countryCode: 'ro' },
  { code: 'sm', name: 'Samoan', countryCode: 'ws' },
  { code: 'gd', name: 'Scots Gaelic', countryCode: 'gb-sct' },
  { code: 'sr', name: 'Serbian', countryCode: 'rs' },
  { code: 'st', name: 'Sesotho', countryCode: 'ls' },
  { code: 'sn', name: 'Shona', countryCode: 'zw' },
  { code: 'sd', name: 'Sindhi', countryCode: 'pk' },
  { code: 'si', name: 'Sinhala', countryCode: 'lk' },
  { code: 'sk', name: 'Slovak', countryCode: 'sk' },
  { code: 'sl', name: 'Slovenian', countryCode: 'si' },
  { code: 'so', name: 'Somali', countryCode: 'so' },
  { code: 'su', name: 'Sundanese', countryCode: 'id' },
  { code: 'sw', name: 'Swahili', countryCode: 'tz' },
  { code: 'sv', name: 'Swedish', countryCode: 'se' },
  { code: 'tg', name: 'Tajik', countryCode: 'tj' },
  { code: 'ta', name: 'Tamil', countryCode: 'in' },
  { code: 'te', name: 'Telugu', countryCode: 'in' },
  { code: 'th', name: 'Thai', countryCode: 'th' },
  { code: 'tr', name: 'Turkish', countryCode: 'tr' },
  { code: 'uk', name: 'Ukrainian', countryCode: 'ua' },
  { code: 'ur', name: 'Urdu', countryCode: 'pk' },
  { code: 'uz', name: 'Uzbek', countryCode: 'uz' },
  { code: 'vi', name: 'Vietnamese', countryCode: 'vn' },
  { code: 'cy', name: 'Welsh', countryCode: 'gb-wls' },
  { code: 'xh', name: 'Xhosa', countryCode: 'za' },
  { code: 'yi', name: 'Yiddish', countryCode: null },
  { code: 'yo', name: 'Yoruba', countryCode: 'ng' },
  { code: 'zu', name: 'Zulu', countryCode: 'za' },
];